### ISSUE TITLE
set up role based views for communities

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#78]
From 12/07/20 & 12/10/20 Meetings:

**Roles**

- Admin (can be more than one): 
  - Can request to create a community to be approved by site admin.
  - Can add / change community details (edit settings).
  - Can add users, assign roles, change roles & delete users.
  - If creating label instances, can not approve them nor export them without Editor's approval.

- Editor:
  - If creating label instances, can not approve them nor export them without Admin's approval.
  - Can not add and remove members.
  - Can not assign/change roles.
  - Does not have access to community settings.

- Viewer:
  - Can not create label instances.
  - Can not add users.
  - Can view only the communities they have joined, the users of those communities, relationships, and labels.

General process for community creator: 
Creator waits for approval from site administrator -> in the meantime can do all admin stuff except for exporting labels to the api. (Add members, create/edit labels, update community information).

**TODO:**
- [x] Figure out the best way to assign these roles (add field to community model for each user instance?)
- [x] How to alter the views based on what role is currently logged in. (Use the Groups model and set up permissions based on the group a user is a part of?) ( Most likely template level).
- [x] Set up the community model to accommodate multiple admins.

Then:
- [ ] Alter the community creation process to accommodate user roles.

_Originally posted by @birbjam in https://github.com/biocodellc/localcontexts_db/issues/71#issuecomment-740254008_
